version: '3.7' # docker-compose file type

services: # Inside is all the defined containers.


  db: # Container
    image: postgres:11
    ports:
      - "54320:5432"
    container_name: postgres_container
    environment:
      POSTGRES_DB: waterMeter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - back
    volumes:
      - my_dbdata:/var/lib/postgresql/data


  web_app: # Container
    build: .
    container_name: node_server_container
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080" # Mounting container
      - "9229:9229" # Mounting data for nodemon connection
    depends_on:
      - db
    restart: always
    networks:
      - front
      - back

networks: # Not really doing anything right now...
  front:
  back:

volumes:
  my_dbdata:
